# Fancy code to automatically instantiate the current robot according to the
# configured robot.
#
# This allows each bot to have the correct robot class with the right
# configuration for that bot, instead of assuming that all bots are identical.
# This is especially useful when prototyping new designs.
#
# This is integrated with the task configuration in .vscode/tasks.json. If you
# really don't want this fancy stuff because you will only ever have one robot
# class, you can delete this file and use your robot class everywhere instead
# of calling `current_robot`.


# Singleton instance that is created by the `current_robot` function. Don't
# access this directly. Just call `current_robot` and let it do its thing.
_CURRENT_ROBOT = None

from base_robot import BaseRobot
from robots import ROBOT_CONFIG


def current_robot() -> BaseRobot:
    """
    Return the current robot.

    Details:
    1) The current robot name is found in the autogenerated
    current_robot_name.py file.
    2) The mapping from robot name to robot class is defined in the
    robots.ROBOT_CONFIG dictionary.
    3) The robot class is instantiated once and cached (in case `current_robot`
    is called multiple times).
    """
    global _CURRENT_ROBOT
    if _CURRENT_ROBOT is not None:
        return _CURRENT_ROBOT

    default_robot_class = BaseRobot

    try:
        from current_robot_name import ROBOT_NAME
    except ImportError as e:
        print("Error: ", e)
        print(
            "Could not import the robot name. Something may be wrong with "
            "the task configuration in .jscode/tasks.json."
        )

    try:
        robot_class = ROBOT_CONFIG[ROBOT_NAME]
    except KeyError as e:
        print("Could not find the robot name:", ROBOT_NAME)
        print("Make sure it is configured in robots.py")
        robot_class = default_robot_class

    _CURRENT_ROBOT = robot_class()
    return _CURRENT_ROBOT
